content:
  - name: prompts
    label: Prompts
    type: collection
    path: prompts            # writes files into /prompts
    create: true
    slug: "{{slug}}"         # no date in filename
    extension: md
    format: frontmatter      # YAML frontmatter + (unused) body
    view:
      fields: [title, locked]

    fields:
      # --- front-matter fields ---
      - { name: id,          label: ID,          type: uuid }
      - { name: locked,      label: Locked,      type: boolean, default: false }
      - { name: title,       label: Title,       type: string }
      - { name: description, label: Description, type: text, required: false }

      # Template saved in front-matter (multi-line string)
      - { name: template,    label: Template,    type: code, options: { language: markdown }, required: true }

      # Input variables (array of objects)
      - name: input_variables
        label: Input variables
        type: list
        fields:
          - { name: name,                label: Name,                type: string }
          - { name: description,         label: Description,         type: string }
          - { name: type,                label: Type,                type: select,
              options: ["string","integer","number","boolean","json"] }
          - { name: required,            label: Required,            type: boolean, default: true }
          - { name: variable_validation, label: Validation regex,    type: string, required: false }

      # Tags = list of strings
      - name: tags
        label: Tags
        type: list
        items: { type: string }

      # Optional metadata
      - { name: created_at,  label: Created at, type: datetime, required: false }
      - { name: updated_at,  label: Updated at, type: datetime, required: false }
      - { name: bookmarked,  label: Bookmarked, type: boolean,  default: false }

