media:
  input: public/prompts-media
  output: /prompts-media

content:
  - name: prompts
    label: Prompts
    type: collection
    path: prompts              # folder in repo root
    create: true
    slug: "{{slug}}"
    extension: md              # write .md files
    format: frontmatter        # YAML front-matter + markdown body
    view:
      fields: [title, locked]

    fields:
      # ── front-matter fields ──
      - { name: id,          label: ID,          type: uuid }
      - { name: locked,      label: Locked,      type: boolean, default: false }
      - { name: title,       label: Title,       type: string }
      - { name: description, label: Description, type: text, required: false }

      # Input variables (array of objects)
      - name: input_variables
        label: Input variables
        type: list
        fields:
          - { name: name,                label: Name,                type: string }
          - { name: description,         label: Description,         type: string }
          - { name: type,                label: Type,                type: select,
              options: ["string","integer","number","boolean","json"] }
          - { name: required,            label: Required,            type: boolean, default: true }
          - { name: variable_validation, label: Validation regex,    type: string, required: false }

      # Tags must be a list of strings (not objects)
      - name: tags
        label: Tags
        type: list
        items:
          type: string

      # Timestamps & bookmark
      - { name: created_at,  label: Created at,  type: datetime, format: "YYYY-MM-DDTHH:mm:ss.SSSZ" }
      - { name: updated_at,  label: Updated at,  type: datetime, format: "YYYY-MM-DDTHH:mm:ss.SSSZ", required: false }
      - { name: bookmarked,  label: Bookmarked,  type: boolean, default: false }

      # ── markdown body becomes the prompt template ──
      - { name: body, label: Template, type: markdown }

