media:        # you can fine‑tune later
  input: public/prompts-media
  output: /prompts-media

content:
  - name: prompts
    label: Prompts
    type: collection          # ← required
    path: prompts             # folder in the repo
    create: true
    slug: "{{slug}}"          # filename without extension
    view:
      fields: [title, locked] # optional sidebar columns
    fields:
      # ── core ──
      - { name: id,          label: ID,          type: uuid }
      - { name: locked,      label: Locked,      type: boolean, default: false }
      - { name: title,       label: Title,       type: string }
      - { name: description, label: Description, type: text, required: false }
      - { name: template,    label: Template,    type: code, options: { language: markdown } }

      # ── input variables list ──
      - name: input_variables
        label: Input variables
        type: list
        fields:
          - { name: name,                label: Name,                type: string }
          - { name: description,         label: Description,         type: string }
          - { name: type,                label: Type,                type: select,
              options: ["string","integer","number","boolean","json"] }
          - { name: required,            label: Required,            type: boolean, default: true }
          - { name: variable_validation, label: Validation regex,    type: string, required: false }

      # ── tags list ──
      - { name: tags, label: Tags, type: list, field: { name: tag, label: Tag, type: string } }

      # ── timestamps & bookmark ──
      - { name: created_at,  label: Created at,  type: date }
      - { name: updated_at,  label: Updated at,  type: date, required: false }
      - { name: bookmarked,  label: Bookmarked,  type: boolean, default: false }

